### ISSUE TITLE
Configure Local Jekyll support

### ISSUE THREAD

**Issue by filfreire** [PortoTestersMeetup/portotestersmeetup.github.io#22] opened 2017-10-24 11:06 UTC
Configure local Jekyll functionality:
- follow https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
- add markdown/html linting job

@FabioCB @filipemcarvalho  FYI

**Comment by filipemcarvalho** [comment] 2017-10-24 11:29
@filfreire 
For the first topic, we could use something like [this](https://www.npmjs.com/package/htmllint) for example, what do you think? 
For the testing part I would suggest add some checks to validate whether all the sections are still there as intended for a start.

**Comment by filfreire** [comment] 2018-01-10 14:16
@filipemcarvalho @FabioCB I'm changing this issue title, and I'll submit a PR.

Github pages work with Jekyll (Ruby) so we need to think in terms of Gemfiles

So something in the line of https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/

to be able to build and test locally and then integrating Travis on #21 

Work is similar to what I did [here](https://github.com/filfreire/filfreire.github.io/commit/89c0de6a9fca1419e4984f29ff0aa5f463000878)

**Comment by filipemcarvalho** [comment] 2018-02-04 01:37
Closed as done in PR #43 👍

**Closed as completed** 2018-02-04 01:37 UTC
